name: Voice_Up
description: A new Flutter project

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  tflite_flutter: ^0.9.0
  tflite_flutter_helper: ^0.3.0
  camera: ^0.9.8+1
  flutter_tts: ^3.2.0
  firebase_core: ^2.25.4
  firebase_storage: ^11.6.5
  video_player: ^2.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Jomhuria
      fonts:
        - asset: assets/fonts/Jomhuria-Regular.ttf
  assets:
    - "assets/videos/A.mp4"
    - "assets/models/ASL-model-tf.tflite"
